name: VelocityCommunications
favicon: null
layout_spectrum: 0.51445
typography_spectrum: 0.9047199382912368
title: Velocity Communications
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#666666'
    - '#5ea51e'
    - '#000000'
    - '#393939'
    - '#008000'
  brandStrength: 0.9601643967907876
  lightness: 0.24317409237846732
  saturation: 0.6046383935026824
  rhythmicContrast: 0.46295669907703996
purpose: []
